# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: ModLoaderTools
      # You may pin to the exact commit or the version.
      # uses: chi-rei-den/ModLoaderTools@3bf2441a06dc05029b5b121e8f1db1744d84e9ad
      uses: chi-rei-den/ModLoaderTools@v1
      with:
        # The command to execute. "setup", "build" or "publish" 
        command: build
        # The path to mod source.
        path: .
